Repository release-it-plugins/workspaces, pull requests merged in 2020-03, with the labels that each got.

#1 Basic implementation of `bump` and `publish` methods
  .eslintrc.js
  __tests__/plugin-test.js
  index.js
  jest.config.js
  jest.setup.js
  package.json
  test.js
  yarn.lock
Labels: enhancement

#2 Fix bug in `resolveWorkspaces`.
  __tests__/plugin-test.js
  index.js
Labels: bug

#3 Update prettier related packages to prettier@2
  index.js
  package.json
  yarn.lock
Labels: internal

#5 Revamp / flesh out README.md.
  README.md
Labels: documentation

#6 Leverage try/catch when bumping (to bubble unrelated errors)
  index.js
Labels: bug

#7 Re-roll yarn.lock.
  yarn.lock
Labels: internal

#8 Refactor publishing process.
  .eslintrc.js
  README.md
  __tests__/plugin-test.js
  index.js
  package.json
  yarn.lock
Labels: enhancement

#9 Add configuration options to README.md.
  README.md
Labels: documentation

#10 Update `package.json`s directly (avoid `npm version`)
  __tests__/plugin-test.js
  index.js
  package.json
  yarn.lock
Labels: internal

#11 Ensure any cross package dependency versions are updated.
  __tests__/plugin-test.js
  index.js
Labels: bug

#12 Ensure publish prompt is useful
  __tests__/plugin-test.js
  index.js
Labels: bug

#13 Ensure OTP prompting works correctly
  __tests__/plugin-test.js
  index.js
Labels: bug

#15 Fix prettier setup.
  .eslintrc.js
  index.js
Labels: internal

#16 Prompt if publishing scoped package fails with private error.
  __tests__/plugin-test.js
  index.js
Labels: enhancement

#17 Do not list private packages in "should we publish" prompt.
  index.js
Labels: bug

#18 Refactor local development flows.
  .github/workflows/ci.yml
  package.json
  yarn.lock
Labels: internal
