Repository release-it-plugins/workspaces, pull requests merged in 2025-06, with the labels that each got.

#119 Drop support for Node < 20
  .github/workflows/ci.yml
  package-lock.json
  package.json
Labels: breaking, codex

#123 Implement templated publishCommand option
  README.md
  index.js
  tests/plugin-test.js
Labels: codex

#127 Fix `pnpm` publishing (and `publishCommand` configuration)
  README.md
  index.js
  package-lock.json
  package.json
  tests/plugin-test.js
Labels: bug, codex

#129 Fix dependency version support to allow any comparison operators (e.g. `>=`)
  index.js
  tests/plugin-test.js
Labels: bug, codex
